ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.solvoku.solvokuservice.AppKt.module

database:
  url: "jdbc:postgresql://localhost:5432/solvoku"
  user: "solvoku"
  password: "solvoku"
  driver: "org.postgresql.Driver"
